[versions]
android-buildTools = "36.0.0"
android-compileSdk = "36"
android-gradlePlugin = "8.12.2"
android-minSdk = "21"
android-targetSdk = "36"
androidx-activity = "1.10.1"
compose = "1.8.2"
dokka = "2.0.0"
jetbrains-androidx-lifecycle = "2.9.3"
# TODO: Migrate to official web source sets once upgraded to Kotlin 2.2.20.
kotlin = "2.2.10"
kotlinx-binaryCompatibilityValidator = "0.18.1"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
mavenPublish = "0.34.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
jetbrains-androidx-lifecycle-runtimeCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-androidx-lifecycle" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibilityValidator" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
